Repository sequentech/release-tool, pull requests merged in 2022-12, with the labels that each got.

#26 Git and documentation fixes
  release.py
Labels: enhancement

#27 Migrating to official ORT Github Action
  .github/workflows/ort.yml
  .ort-data/curations-dir/bsd_license.yml
  .ort-data/curations-dir/distlib.yml
  .ort-data/curations-dir/drangandroptouch.yml
  .ort-data/curations-dir/fractionjs.yml
  .ort-data/curations-dir/java.yml
  .ort-data/curations-dir/jszip.yml
  .ort-data/curations-dir/psycopg2-binary.yml
  .ort-data/curations-dir/pycryptodomex.yml
  .ort-data/curations-dir/reportlab.yml
  .ort-data/curations-dir/rng-js.yml
  .ort-data/curations-dir/voting-booth.yml
  .ort-data/disclosure_document.ftl
  .ort-data/license-classifications.yml
  .ort-data/rules.kts
Labels: infrastructure

#28 Migrating to official ORT Github Action
  .github/workflows/ort.yml
  .ort-data/curations-dir/bsd_license.yml
  .ort-data/curations-dir/distlib.yml
  .ort-data/curations-dir/drangandroptouch.yml
  .ort-data/curations-dir/fractionjs.yml
  .ort-data/curations-dir/java.yml
  .ort-data/curations-dir/jszip.yml
  .ort-data/curations-dir/psycopg2-binary.yml
  .ort-data/curations-dir/pycryptodomex.yml
  .ort-data/curations-dir/reportlab.yml
  .ort-data/curations-dir/rng-js.yml
  .ort-data/curations-dir/voting-booth.yml
  .ort-data/disclosure_document.ftl
  .ort-data/license-classifications.yml
  .ort-data/rules.kts
Labels: infrastructure

#29 Migrating to official ORT Github Action
  .github/workflows/ort.yml
  .ort-data/curations-dir/bsd_license.yml
  .ort-data/curations-dir/distlib.yml
  .ort-data/curations-dir/drangandroptouch.yml
  .ort-data/curations-dir/fractionjs.yml
  .ort-data/curations-dir/java.yml
  .ort-data/curations-dir/jszip.yml
  .ort-data/curations-dir/psycopg2-binary.yml
  .ort-data/curations-dir/pycryptodomex.yml
  .ort-data/curations-dir/reportlab.yml
  .ort-data/curations-dir/rng-js.yml
  .ort-data/curations-dir/voting-booth.yml
  .ort-data/disclosure_document.ftl
  .ort-data/license-classifications.yml
  .ort-data/rules.kts
Labels: infrastructure

#31 Bump certifi from 2021.10.8 to 2022.12.7 (#30)
  requirements.txt
Labels: dependencies
